### ISSUE TITLE
Archives are not browsable

### ISSUE THREAD

**Issue by mikrosk** [doitarchive/doit_f030#1]
It's pretty trivial to do - if you give me collaborator access, I'll fix it for you in all repos.

EDIT: I mean browsable so one can browse them as a website, not html source code.

**Comment by ragnar76** [comment]
yeah, there is no index.html. But there is some work on the files too because they link to doitf030.html. i suggest, we create a new branch and change the entire thing into something new (and more webserver friendly)

**Comment by mikrosk** [comment]
How do you test it? I wanted to setup a "web view" (using github's facilities) but don't have access to project's settings. After setting it up you could see the result directly at https://doitarchive.github.io/doit_f030

**Comment by ragnar76** [comment]
well, i use a local apache webserver.

**Comment by mikrosk** [comment]
Actually, I had some spare time & energy so I fixed it on my own: https://mikrosk.github.io/doitarchive

You can find sources here: https://github.com/mikrosk/doitarchive
